# Generated by Django 4.2 on 2023-05-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modellista',
            options={'verbose_name': 'o que fazer', 'verbose_name_plural': 'o que fazer'},
        ),
        migrations.RemoveField(
            model_name='modellista',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='modellista',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='modellista',
            name='mes',
        ),
        migrations.AddField(
            model_name='modellista',
            name='data',
            field=models.DateField(default='2023-05-03', verbose_name='data_tarefa'),
            preserve_default=False,
        ),
    ]
