# Generated by Django 4.2 on 2023-05-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modellista_options_remove_modellista_ano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modellista',
            old_name='data',
            new_name='data_tarefa',
        ),
    ]
